# Generated by Django 5.2.1 on 2025-06-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/resources/thumbnails/"
            ),
        ),
    ]
