# Generated by Django 5.2.1 on 2025-06-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0002_resources_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resources",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pdf", "PDF"),
                    ("doc", "Document"),
                    ("link", "Link"),
                    ("video", "Video"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
