# Generated by Django 5.2.1 on 2025-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0003_resources_link_alter_resources_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resources",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("pdf", "PDF"), ("doc", "Document"), ("link", "Link")],
                max_length=10,
                null=True,
            ),
        ),
    ]
