# Generated by Django 5.2.1 on 2025-06-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0004_alter_resources_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
