# Generated by Django 5.2.1 on 2025-06-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="ccreated_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="is_saved",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="is_saved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
