# Generated by Django 5.2.1 on 2025-06-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_chatmessage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("advisior", "Advisior"), ("agent", "Agent")],
                default="advisior",
                max_length=15,
                null=True,
            ),
        ),
    ]
