# Generated by Django 5.2.1 on 2025-05-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("admin", "admin"), ("user", "user")],
                default="user",
                max_length=20,
                null=True,
            ),
        ),
    ]
