# Generated by Django 5.2.1 on 2025-06-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_language_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(null=True, upload_to="uploads/users/images"),
        ),
    ]
